# Generated by Django 5.2.1 on 2025-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated skills (e.g. Python, Fundraising, Event Planning)",
                max_length=255,
            ),
        ),
    ]
