# Generated by Django 5.2.4 on 2025-09-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='skills_required',
            new_name='skills_recommended',
        ),
    ]
